ui: mocha-qunit
server: ./test/support/server.js
browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: safari
    version: 5..latest
  - name: ie
    version: 10..latest
